language: node_js
sudo: false
dist: xenial
node_js:
  - "10"
  - "12"
services:
  - postgresql
before_script:
  - psql -c 'create database testdb;' -U postgres
script:
  - npm install migrat
  - TRAVIS_CI=1 make test
